Remove bound on JAX/Diffrax versions
Qiskit-Extensions/qiskit-dynamics pull request #266
Opened 2023-10-12 23:38 UTC by DanPuzzuoli

### Summary

As it is unclear when the bug causing an error in the perturbation module will get fixed in JAX, I just tried returning to the issue and have figured out a simple workaround to bypass the bug. I realistically should have tried this sooner but I didn't realize the issue would hang for this long.

The workaround fixes the perturbation module, but there are now many errors/warnings coming up in many different tests. This is to be expected - there have been over 10 minor releases of JAX since we put a bound on the version. I'll need to make my way through each folder and figure out how to fix it. 

### Details and comments

2023-10-16 16:28 UTC, DanPuzzuoli commented
It seems the complex -> real casting warnings only ever occur in jitted functions, which means this is probably some weird behaviour with JAX transformations (i.e. these warnings don't get raised if the function is not compiled). Need to try to find a minimal example to understand what's going on.

2023-10-20 21:52 UTC, DanPuzzuoli commented
As it currently stands:

- The workaround is implemented in `dyson_magnus.py` in the function `_setup_dyson_rhs_jax`.
- The import warning about JAX version restrictions has been removed, and the bounds in version bounds in files like `setup.py` and the test environment setups have been removed.
- A test has been added to `test_dyson_magnus.py` that contains a minimal reproduction of the error with the original version of `_setup_dyson_rhs_jax`. The test is setup to pass if an exception is thrown when executing this code. Once this test starts failing, we will know that the original version of `_setup_dyson_rhs_jax` _should_ work again, and at that point we can revert it. (The documentation in the test states this.)
- I've added a release note to this PR with an upgrade note stating that users should now use the latest version of JAX. Unfortunately, the complex casting warning issue hasn't been resolved yet, and for now I've added a "known issue" note in relation to this warning.

2023-10-27 05:46 UTC, to24toro requested changes

2023-10-27 05:46 UTC, to24toro commented on releasenotes/notes/update-jax-a50ce1b7d6b47219.yaml
> +    A JAX warning about casting complex values to real is raised when when computing gradients of
```suggestion
    A JAX warning about casting complex values to real is raised when computing gradients of
```

2023-10-30 04:25 UTC, to24toro approved these changes

2023-10-30 14:12 UTC, merged