RWA arraylias conversion
Qiskit-Extensions/qiskit-dynamics pull request #296
Opened 2023-12-14 23:56 UTC by DanPuzzuoli

### Summary

Converting `rotating_wave_approximation.py` to use arraylias.

I ended up adding the helper functions `_to_dense` and `_to_dense_list` in `arraylias/alias.py` as the `to_array` method had been being used in to convert everything to dense, and we need something analogous. 

### Details and comments

tests that need to be run before merge:

test.dynamics.models (whole folder)
test.dynamics.arraylias (whole folder)

2023-12-16 08:28 UTC, to24toro requested changes
Thanks. Almost looking good to me.

- Regarding alias.py, it might be better to add tests about `_to_dense`and `_to_dense_list`.

2023-12-18 11:11 UTC, DanPuzzuoli commented on qiskit_dynamics/models/rotating_wave_approximation.py
>  ):
The return type for `get_rwa_operators` should be `ArrayLike` and the return type for `get_rwa_signals` is `SignalList`. Just added these type hints.

2023-12-18 12:37 UTC, DanPuzzuoli commented
@to24toro I've updated the type hints and added tests for `_to_dense` and `_to_dense_list`.

I had to force push as I'm working from my personal laptop and had forgotten to update the `git config` with my username on commit [7d21240](https://github.com/Qiskit-Extensions/qiskit-dynamics/pull/296/commits/7d21240b02152c9e94cde1868678e8141ca0c3ca), which triggered the CLA message.

2023-12-18 12:41 UTC, to24toro commented on qiskit_dynamics/models/rotating_wave_approximation.py
>  ):
Thank you. Regarding `frame_freqs`, it's my mistake and I referred a wrong part.

2023-12-18 12:44 UTC, to24toro approved these changes
LGTM!

2023-12-18 12:46 UTC, merged