Default t_span available for `DynamicsBackend.solve`
Qiskit-Extensions/qiskit-dynamics pull request #353
Opened 2024-04-09 02:02 UTC by arthurostrauss

### Summary
This PR introduces the possibility to use `DynamicsBackend.solve()`without having to specify a `t_span`argument explicitly. If it is not specified, the default `t_span`is inferred from the provided `solve_input` to create a `t_span`of the form [0, solve_input.duration] for each solve_input in the provided list. This can be useful for simulating easily a full `QuantumCircuit`s as the process of converting them to `Schedule` is already done behind the scenes. 

### Details and comments

2024-04-09 02:35 UTC, arthurostrauss commented
I'm not really sure why the tests are failing, they do not seem related to the proposed changes at all.

2024-04-09 02:43 UTC, DanPuzzuoli commented
> I'm not really sure why the tests are failing, they do not seem related to the proposed changes at all.

I think it may be due to the latest qutip update, which occurred after the last time the automated tests were run - I can look into it tomorrow.

2024-04-09 21:07 UTC, DanPuzzuoli commented
Okay just merged a fix for the qutip qobj handling in #354 , you can try again after updating your branch.

2024-04-24 15:20 UTC, DanPuzzuoli commented
> @DanPuzzuoli Any updates on this?

Hey @arthurostrauss - if this is ready for review please request my review on the right :).

2024-04-26 08:18 UTC, arthurostrauss commented
@DanPuzzuoli It seems I am not able to add any reviewers on the panel unfortunately (it indicates that I am not authorised to edit the PR). Can you assign yourself to the review?

2024-04-26 14:26 UTC, DanPuzzuoli requested changes

2024-04-26 14:26 UTC, DanPuzzuoli commented on qiskit_dynamics/backend/dynamics_backend.py
> +                    interval is set to [[0, input.duration] for input in solve_input]].
```suggestion
                    interval is set to ``[[0, input.duration] for input in solve_input]]``.
```

2024-04-26 14:26 UTC, DanPuzzuoli commented on releasenotes/notes/default_tspan_backend_solve-b1ad23f6ea291474.yaml
> +    duration in advance.
```suggestion
    ``DynamicsBackend.solve()`` method can now work without specifying a ``t_span`` argument. 
    The default ``t_span`` is set to be ``[0, solve_input.duration]`` for each provided ``solve_input``.
    This allows users to solve the dynamics of a quantum circuit without having to specify its
    duration in advance.
```

2024-04-26 15:46 UTC, DanPuzzuoli approved these changes

2024-04-26 15:46 UTC, merged